<?php

declare(strict_types=1);

$title=$pageTitle??$store['name'];$description=$pageDescription??$store['description'];$path=$currentPath??current_path();$theme=$store['theme'];
?>
<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=e($description)?>"><meta name="theme-color" content="<?=e($theme['brand'])?>"><link rel="canonical" href="<?=e(absolute_url($path,$store))?>"><meta property="og:type" content="website"><meta property="og:title" content="<?=e($title)?>"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="<?=e(absolute_url($path,$store))?>"><title><?=e($title)?></title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/css/app.css"></head>
<body style="--brand:<?=e($theme['brand'])?>;--brand-dark:<?=e($theme['brand_dark'])?>;--accent:<?=e($theme['accent'])?>;--surface:<?=e($theme['surface'])?>;--surface-alt:<?=e($theme['surface_alt'])?>;--text:<?=e($theme['text'])?>;--muted:<?=e($theme['muted'])?>;"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="container header-inner"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"><?=e(strtoupper(substr($store['short_name'],0,1)))?></span><span><?=e($store['name'])?></span></a><nav aria-label="Primary navigation"><ul class="nav-list"><?php foreach($store['navigation'] as $item):?><li><a class="<?=$path===$item['href']?'active':''?>" href="<?=e($item['href'])?>"><?=e($item['label'])?></a></li><?php endforeach;?></ul></nav><a class="cart-link" href="/cart">Basket <span><?=cart_count()?></span></a></div></header>
<?php if($flash):?><div class="flash <?=e((string)($flash['type']??'info'))?>" role="status"><div class="container"><?=e((string)($flash['message']??''))?></div></div><?php endif;?>
<main id="main"><?=$content?></main><footer class="site-footer"><div class="container footer-grid"><div><a class="brand footer-brand" href="/"><span class="brand-mark" aria-hidden="true"><?=e(strtoupper(substr($store['short_name'],0,1)))?></span><span><?=e($store['name'])?></span></a><p><?=e($store['tagline'])?></p></div><div><h2 class="footer-heading">Contact</h2><p><a href="mailto:<?=e($store['contact_email'])?>"><?=e($store['contact_email'])?></a></p></div><div><h2 class="footer-heading">Information</h2><p><a href="/privacy">Privacy notice</a><br><a href="/terms">Terms of sale</a></p></div><div><h2 class="footer-heading">Social</h2><p class="social-links"><?php foreach($store['social'] as $social):?><a href="<?=e($social['href'])?>" target="_blank" rel="noopener noreferrer"><?=e($social['label'])?></a><?php endforeach;?></p></div></div><div class="container footer-bottom"><p>&copy; <?=date('Y')?> <?=e($store['name'])?>. All rights reserved.</p></div></footer></body></html>
